ALPACA_KEY = "PK1C22RJITMMTBC4D7YY"
ALPACA_SECRET = "RQbTAeVxemXFXkx0e0J8TafewGnUvEHvyYhqPdiK"
OPENAI_KEY = "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"
